### ISSUE TITLE
Feature request: Implement Vimperator style hintchars

### ISSUE THREAD

**Issue by redblade7** [madand/pentadactyl-pm#4]
Hi,

Vimperator has the option to change the hint characters, including letters A-Z, either alphabetically, "home row," or "smart" ordering.

In the case of the alphabetical ordering, after Z, the hints start at AA, AB, etc.

Regardless of the order, it's a lot easier to type in one character than two, and there is usually more than 9 hints on a page, but rarely more than 26.

It would be a good idea I think to add Vimperator's hintchars option to Pentadactyl, as in hint mode, one character is a lot quicker and easier to type than two.

Thank you!

![toomc](https://user-images.githubusercontent.com/15269155/27889510-de8405f6-61ba-11e7-96a0-d158f287e854.png)

**Comment by redblade7** [comment]
Pentadactyl has a "hintkeys" option which allows you to enter your own ordering manually, though it appears to skip over A.

EDIT: "hintkeys" apparently ignores the first character. You can get access to A by setting hintkeys to "0abcdefghijklmnopqrstuvwxyz"

EDIT: "hintkeys" apparently is case sensitive. Attempting to use a different case results in bizarre behavior.

**Comment by madand** [comment]
@redblade7 I am glad to hear you found about the `hintkeys` option. I can confirm the mentioned quirks too.

But this port is intended to make Pentadactyl work in Pale Moon, other feature requests or not Pale Moon specific bugs should be reported upstream https://github.com/5digits/dactyl. Sorry for the confusion, I will add a notice about this into the repo readme.

**Comment by redblade7** [comment]
I didn't think Pentadactyl was being maintained any more except for Pale Moon.

Can you please let me know when the issue is added to the main Pentadactyl repo and provide a link?

Thank you!

**Comment by madand** [comment]
@redblade7 it is maintained, but activity is rather very low there. To clarify things, I am in no way involved in the Pentadactyl development, it is very big and complex piece of software.

Regarding posting an issue in the upstream repo. I expect the interested party (in this case it's you) to post the issue there and track its progress.
